openapi: 3.0.0
info:
  title: La Procure - API Gestion
  version: '1.0'
  description: |
    ##API de gestion:
    * gestion du périmètre La Procure
    * gestion de la "blacklist"
  contact:
    name: Frédéric vergez
    email: fvergez@electre.com
servers:
  - url: 'https://api.electre.com/v1.0'
    description: Environnement de production
paths:
  '/blacklist/{ean}':
    parameters:
      - type: string
        name: ean
        in: path
        required: true
        schema:
          type: integer
        description: EAN cible
    get:
      summary: "Vérificiation d'appartenance à la blacklist"
      tags:
        - blacklist
      responses:
        '204':
          description: "No Content: si l'EAN cible a été trouvé dans la blacklist"
        '404':
          description: "Not Found: si l'EAN cible n'est pas trouvé dans la blacklist"
      operationId: get-blacklist-ean
      description: "Vérifie si l'EAN donné est présent dans la blacklist."
      security:
        - idp electre:
            - webapi
    put:
      summary: "Ajout d'un élément à la blacklist"
      operationId: put-blacklist-ean
      responses:
        '201':
          description: "Created: Si l'ajout de l'EAN est un succés"
      description: "Ajoute l'EAN cible à la blacklist."
      security:
        - idp electre:
            - webapi
      tags:
        - blacklist
    delete:
      summary: "Retrait d'un élément de la blacklist"
      operationId: delete-blacklist-ean
      responses:
        '200':
          description: "OK: si l'EAN a été supprimé de la blacklist"
        '404':
          description: "Not Found: Si l'EAN ne peut pas etre retiré de la blacklist (non-présent)"
      security:
        - idp electre:
            - webapi
      description: "Enlève l'EAN cible de la blacklist."
      tags:
        - blacklist
  '/clientData/{ean}':
    parameters:
      - schema:
          type: string
        name: ean
        in: path
        required: true
        description: EAN Cible
    put:
      summary: "Ajout d'une notice au périmètre"
      operationId: put-clientData-ean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Ajout de données de gestion:
                  value:
                    prixttc: 12.45
                    prixpromo: 11.5
                    stock: 5
      description: |
        Ajout d'un EAN au périmètre.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              client-data:
                value:
                  prixttc: 12.45
                  prixpromo: 11.5
                  stock: 5
        description: Il est possible de spécifier des options de gestion dans le corps de la requete
      tags:
        - init
      security:
        - idp-electre:
            - webapi
    delete:
      summary: "Retrait d'une notice du périmètre"
      operationId: delete-clientData-ean
      responses:
        '204':
          description: No Content
      description: "Retrait d'une notice du périmètre préalablement ajouté via PUT *(et via son EAN)*"
      tags:
        - init
      security:
        - idp-electre:
            - webapi
components:
  schemas: {}
  securitySchemes:
    idp-electre:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes:
            webapi: Scope OIDC obligatoire
