openapi: 3.0.0
info:
  title: procure
  version: '1.0'
  description: 'API spécifique "La Procure"'
servers:
  - url: 'https://api.electre.com/v1.0'
    description: Environnement de production
paths:
  '/books/{id-or-ean}':
    parameters:
      - schema:
          type: string
        name: id-or-ean
        in: path
        required: true
        description: EAN ou identifiant de la notice
    get:
      summary: "Récuperation d'une notice"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples: {}
      operationId: get-books-id-or-ean
      description: 'Recupére une notice via son identifiant **ou** son EAN.'
      security:
        - id-electre:
            - webapi
      tags:
        - notice
      requestBody: {}
  '/books/{id}/covers':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: EAN ou identifiant de la notice
    get:
      summary: Liste des couvertures pour une notice
      tags:
        - notice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-books-id-or-ean-covers
      description: |-
        Liste des couvertures disponibles pour un ID donné.

        Si plusieurs couvertures sont disponibles, ellessont listées par EAN.
      security:
        - id-electre:
            - webapi
  '/books/{id}/covers/{ean}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        schema:
          type: string
        description: Identifiant de la notice
      - type: string
        name: ean
        in: path
        required: true
        schema:
          type: string
        description: "EAN cible pour la notice d'identifiant `id`"
    get:
      summary: "Récupération d'une couverture"
      tags:
        - notice
      responses:
        '200':
          description: |-
            OK

            Le lien direct vers l'image de couverture est contenu dans le champ `href` pour la valeur `media` de `rel`.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-books-id-covers-ean
      description: "Récupère la couverture pour la notice idenitifiée `id` et l'EAN."
      security:
        - id-electre:
            - webapi
      parameters:
        - schema:
            type: string
          in: query
          name: alt
          description: "`alt=media` retourne l'image au format JPEG directement"
        - schema:
            type: integer
            default: '400'
          in: query
          name: maxWidth
          description: "La largeur maximale de l'image en pixels"
        - schema:
            type: integer
          in: query
          name: maxHeight
          description: "La hauteur maximale de l'image en pixels"
  '/blacklist/{ean}':
    parameters:
      - type: string
        name: ean
        in: path
        required: true
        schema:
          type: string
        description: EAN cible
    get:
      summary: "Vérificiation d'appartenance à la blacklist"
      tags:
        - blacklist
      responses:
        '204':
          description: "No Content: si l'EAN cible a été trouvé dans la blacklist"
        '404':
          description: "Not Found: si l'EAN cible n'est pas trouvé dans la blacklist"
      operationId: get-blacklist-ean
      description: "Vérifie si l'EAN donné est présent dans la blacklist."
      security:
        - idp electre:
            - webapi
    put:
      summary: "Ajout d'un élément à la blacklist"
      operationId: put-blacklist-ean
      responses:
        '201':
          description: "Created: Si l'ajout de l'EAN est un succés"
      description: "Ajoute l'EAN cible à la blacklist."
      security:
        - idp electre:
            - webapi
      tags:
        - blacklist
        - beta
    delete:
      summary: "Retrait d'un élément de la blacklist"
      operationId: delete-blacklist-ean
      responses:
        '200':
          description: "OK: si l'EAN a été supprimé de la blacklist"
        '404':
          description: "Not Found: Si l'EAN ne peut pas etre retiré de la blacklist (non-présent)"
      security:
        - idp electre:
            - webapi
      description: "Enlève l'EAN cible de la blacklist."
      tags:
        - blacklist
        - beta
components:
  schemas: {}
  securitySchemes:
    id-electre:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://idp2.electre.com/connect/token'
          refreshUrl: ''
          scopes:
            webapi: ''
